### ISSUE TITLE
Creating a new blockset, I get the following error on server load. Issue does not appear if I have 5 BlockForms but as soon as I add 6th I get this error.

### ISSUE THREAD

**Issue by FishAus** [StrangeLoopGames/EcoModKit#5]
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.SaveGIF(String name, Int32 width, Int32 height, Func`3 pixelFunc, Color[] pallette, Boolean animate, Boolean backup)
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.GenerateTerrainImage()
   at Eco.Simulation.WorldLayers.History.WorldLayerHistory.Update()
   at Eco.Simulation.EcoSim.CollectStats()
   at Eco.Core.Plugins.TickTimeUtil.TimeSubprocess(Action func)
   at Eco.Simulation.EcoSim.DoTick(TickSample tick)
   at Eco.Simulation.EcoSim.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by FishAus** [comment]
moiving this to the main git with more information
